Repository slamapp/server, pull requests merged in 2022-06, with the labels that each got.

#41 fix/user 40 - 존재하지 않는 유저페이지에 접근 시 구체적인 에러메세지 생성
  src/main/java/org/slams/server/common/error/GlobalExceptionHandler.java
  src/main/java/org/slams/server/user/controller/UserController.java
Labels: 백앤드, 🛠fix

#42 feature/management 29 - 처리 대기 중 또는 완료된 새 농구장 목록 조회 api
  src/main/java/org/slams/server/court/controller/CourtController.java
  src/main/java/org/slams/server/court/dto/request/CourtInsertRequestDto.java
  src/main/java/org/slams/server/court/dto/request/NewCourtInsertRequest.java
  src/main/java/org/slams/server/court/dto/response/CourtInsertResponseDto.java
  src/main/java/org/slams/server/court/dto/response/NewCourtDto.java
  src/main/java/org/slams/server/court/dto/response/NewCourtInDoneLookUpResponse.java
  src/main/java/org/slams/server/court/dto/response/NewCourtInReadyLookUpResponse.java
  src/main/java/org/slams/server/court/dto/response/NewCourtInsertResponse.java
  src/main/java/org/slams/server/court/service/CourtService.java
  src/main/java/org/slams/server/court/service/NewCourtService.java
  src/main/java/org/slams/server/favorite/controller/FavoriteController.java
  src/main/java/org/slams/server/favorite/dto/request/FavoriteInsertRequestDto.java
  src/main/java/org/slams/server/favorite/service/FavoriteService.java
  src/main/java/org/slams/server/management/controller/ManagementController.java
  src/main/java/org/slams/server/reservation/dto/request/ReservationInsertRequestDto.java
  src/main/java/org/slams/server/user/dto/response/CreatorDto.java
  src/test/java/org/slams/server/court/controller/CourtControllerTest.java
  src/test/java/org/slams/server/management/controller/ManagementControllerTest.java
Labels: 🙌리뷰요청, 백앤드, ✨feat, 🛠fix

#44 fix/notification 43 무한 스크롤 lastId 값 변경
  src/main/java/org/slams/server/chat/repository/ChatContentsRepository.java
  src/main/java/org/slams/server/chat/repository/UserChatroomMappingRepository.java
  src/main/java/org/slams/server/chat/service/ChatContentsService.java
  src/main/java/org/slams/server/chat/service/ChatroomMappingService.java
  src/main/java/org/slams/server/common/api/CursorPageRequest.java
  src/main/java/org/slams/server/common/api/CursorPageResponse.java
  src/main/java/org/slams/server/court/service/NewCourtService.java
  src/main/java/org/slams/server/follow/service/FollowService.java
  src/main/java/org/slams/server/notification/repository/NotificationRepository.java
  src/main/java/org/slams/server/notification/service/NotificationService.java
  src/main/java/org/slams/server/reservation/service/ReservationService.java
  src/main/java/org/slams/server/user/service/UserService.java
  src/test/java/org/slams/server/chat/service/ChatroomMappingServiceTest.java
  src/test/java/org/slams/server/follow/controller/FollowControllerTest.java
  src/test/java/org/slams/server/management/controller/ManagementControllerTest.java
Labels: 🛠fix

#54 docs/common 53 - 프로젝트 내에 있는 불필요한 파일 삭제
  slam.png
  slam.sql
  slam2.mwb
  slam2.mwb.bak
  slam2.png
  slam_tmep.mwb
Labels: 백앤드, 🧹chore

#50 docs/readme - client git repo url 최신화
  README.md
Labels: 🧹chore

#56 fix/favorite 55 - response의 id type을 Long -> String으로 변환
  src/main/java/org/slams/server/chat/convertor/ChatContentConvertor.java
  src/main/java/org/slams/server/chat/convertor/ChatroomMappingConvertor.java
  src/main/java/org/slams/server/chat/repository/CourtChatroomMappingRepository.java
  src/main/java/org/slams/server/chat/repository/UserChatroomMappingRepository.java
  src/main/java/org/slams/server/common/BaseEntity.java
  src/main/java/org/slams/server/common/error/exception/ErrorCode.java
  src/main/java/org/slams/server/court/dto/response/CourtDetailDto.java
  src/main/java/org/slams/server/court/dto/response/CourtInMapDto.java
  src/main/java/org/slams/server/court/dto/response/NewCourtDto.java
  src/main/java/org/slams/server/court/dto/response/NewCourtResponse.java
  src/main/java/org/slams/server/favorite/controller/FavoriteController.java
  src/main/java/org/slams/server/favorite/dto/request/FavoriteInsertRequest.java
  src/main/java/org/slams/server/favorite/dto/request/FavoriteInsertRequestDto.java
  src/main/java/org/slams/server/favorite/dto/response/FavoriteDeleteResponseDto.java
  src/main/java/org/slams/server/favorite/dto/response/FavoriteInsertResponse.java
  src/main/java/org/slams/server/favorite/dto/response/FavoriteInsertResponseDto.java
  src/main/java/org/slams/server/favorite/dto/response/FavoriteLookUpResponse.java
  src/main/java/org/slams/server/favorite/dto/response/FavoriteSelectResponseDto.java
  src/main/java/org/slams/server/favorite/entity/Favorite.java
  src/main/java/org/slams/server/favorite/exception/FavoriteNotFoundException.java
  src/main/java/org/slams/server/favorite/repository/FavoriteRepository.java
  src/main/java/org/slams/server/favorite/service/FavoriteService.java
  src/main/java/org/slams/server/follow/dto/response/FollowerResponse.java
  src/main/java/org/slams/server/follow/dto/response/FollowingResponse.java
  src/main/java/org/slams/server/notification/convertor/NotificationConvertor.java
  src/main/java/org/slams/server/reservation/dto/response/ReservationInsertResponseDto.java
  src/main/java/org/slams/server/reservation/dto/response/ReservationResponseDto.java
  src/main/java/org/slams/server/reservation/dto/response/ReservationUpcomingResponseDto.java
  src/main/java/org/slams/server/reservation/dto/response/ReservationUpdateResponseDto.java
  src/main/java/org/slams/server/reservation/service/ReservationService.java
  src/main/java/org/slams/server/user/dto/response/DefaultUserDto.java
  src/main/java/org/slams/server/user/dto/response/UserProfileResponse.java
  src/main/java/org/slams/server/user/dto/response/UserResponse.java
  src/main/java/org/slams/server/user/dto/response/UserWithoutEmailDto.java
  src/main/java/org/slams/server/user/service/UserService.java
  src/test/java/org/slams/server/court/controller/CourtControllerTest.java
  src/test/java/org/slams/server/favorite/controller/FavoriteControllerTest.java
  src/test/java/org/slams/server/follow/controller/FollowControllerTest.java
  src/test/java/org/slams/server/reservation/controller/ReservationControllerTest.java
Labels: 백앤드, 🛠fix

#52 feat/common 37 - swagger authorization button 추가
  pom.xml
  src/main/java/org/slams/server/common/config/SwaggerConfig.java
Labels: 백앤드, ✨feat

#46 feat/notification 47 웹소켓으로 받은 요청을 restapi로 받기 (swagger 내용 추가)
  src/main/java/org/slams/server/chat/repository/UserChatroomMappingRepository.java
  src/main/java/org/slams/server/common/error/exception/ErrorCode.java
  src/main/java/org/slams/server/follow/exception/FollowOneselfException.java
  src/main/java/org/slams/server/notification/controller/NotificationController.java
  src/main/java/org/slams/server/notification/controller/NotificationWebSocketController.java
  src/main/java/org/slams/server/notification/service/NotificationService.java
  src/main/java/org/slams/server/notification/service/WebsocketNotificationService.java
Labels: 🙌리뷰요청, ✨feat
