Repository slamapp/server, pull requests merged in 2022-11, with the labels that each got.

#79 fix/reservation 78 - proxy상태일 때 내부 상태값에 접근했을 때 발생하는 에러 해결
  src/main/java/org/slams/server/reservation/repository/ReservationRepository.java
Labels: 🛠fix

#81 Revert "fix/user 73 - user 이메일 수집 철회"
  src/main/java/org/slams/server/user/dto/response/DefaultUserInfoResponse.java
  src/main/java/org/slams/server/user/dto/response/MyProfileLookUpResponse.java
  src/main/java/org/slams/server/user/entity/User.java
  src/main/java/org/slams/server/user/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/org/slams/server/user/oauth/jwt/Jwt.java
  src/main/java/org/slams/server/user/service/OAuthUserService.java
  src/main/resources/application.yaml
Labels: ⚠️급한 처리⚠️

#83 fix/reservation 82 - 지난 예약 조회 시 500에러(proxy 초기화 문제) 수정
  src/main/java/org/slams/server/reservation/repository/ReservationRepository.java
Labels: 🛠fix

#85 release 84 - 11월 26일 운영 배포
  .github/workflows/maven.yml
  src/main/java/org/slams/server/reservation/dto/response/ReservationByCourtAndDateResponse.java
  src/main/java/org/slams/server/reservation/repository/ReservationRepository.java
Labels: 백앤드

#87 release 85 - 11월 26일 운영배포 2
  src/main/java/org/slams/server/reservation/repository/ReservationRepository.java
  src/main/java/org/slams/server/user/dto/response/DefaultUserInfoResponse.java
  src/main/java/org/slams/server/user/dto/response/MyProfileLookUpResponse.java
  src/main/java/org/slams/server/user/entity/User.java
  src/main/java/org/slams/server/user/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/org/slams/server/user/oauth/jwt/Jwt.java
  src/main/java/org/slams/server/user/service/OAuthUserService.java
  src/main/resources/application.yaml
Labels: 백앤드, 🚀배포
